


=====================================================================
gen ds_info
ds_config:
         use_dummy_gt: 0
      use_custom_data: 0
              ds_name: 'PascalContext'
       gen_ds_info_fn: [function_handle]
    ds_info_cache_dir: '../datasets/PascalContext'

file not exist:../datasets/PascalContext/my_dataset_info.mat
../datasets/PascalContext/Truth/Train
../datasets/PascalContext/Truth/Val
{Error using <a href="matlab:matlab.internal.language.introspective.errorDocCallback('my_gen_ds_info_pascalcontext', '/Users/samlerner/Projects/refinenet/main/my_gen_ds_info_pascalcontext.m', 16)" style="font-weight:bold">my_gen_ds_info_pascalcontext</a> (<a href="matlab: opentoline('/Users/samlerner/Projects/refinenet/main/my_gen_ds_info_pascalcontext.m',16,0)">line 16</a>)
Assertion failed.

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('gen_dataset_info', '/Users/samlerner/Projects/refinenet/main/gen_dataset_info.m', 15)" style="font-weight:bold">gen_dataset_info</a> (<a href="matlab: opentoline('/Users/samlerner/Projects/refinenet/main/gen_dataset_info.m',15,0)">line 15</a>)
        ds_info=ds_config.gen_ds_info_fn(ds_config);
        
Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('demo_refinenet_train', '/Users/samlerner/Projects/refinenet/main/demo_refinenet_train.m', 129)" style="font-weight:bold">demo_refinenet_train</a> (<a href="matlab: opentoline('/Users/samlerner/Projects/refinenet/main/demo_refinenet_train.m',129,0)">line 129</a>)
ds_info=gen_dataset_info(ds_config);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('run', '/Applications/MATLAB_R2018a.app/toolbox/matlab/lang/run.m', 91)" style="font-weight:bold">run</a> (<a href="matlab: opentoline('/Applications/MATLAB_R2018a.app/toolbox/matlab/lang/run.m',91,0)">line 91</a>)
evalin('caller', strcat(script, ';'));
} 
run demo_refinenet_train.m
